---
- name: Check if disk exists
  command: "file -sL /dev/disk/by-id/google-{{ disk_name }}"
  register: disk_exists
  changed_when: "'UUID=' not in disk_exists.stdout"

- name: Format disk
  command: "mkfs.ext4 -m 0 -F -E lazy_itable_init=0,lazy_journal_init=0,discard /dev/disk/by-id/google-{{ disk_name }}"
  when: "'UUID=' not in disk_exists.stdout"

- name: Create mount directory
  file:
    dest: "{{ mount_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: "'UUID=' not in disk_exists.stdout"

- name: Mount drive
  mount:
    path: "{{ mount_directory }}"
    src: "/dev/disk/by-id/google-{{ disk_name }}"
    fstype: ext4
    opts: discard,defaults,nofail
    dump: "0"
    passno: "2"
    state: mounted
  when: "'UUID=' not in disk_exists.stdout"
